project:
  type: website

website:
  title: "Quadrants Forum"
  site-url: https://actionable-blog-posts.netlify.app/
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - icon: rss
        href: index.html
format:
  html:
    theme:
      dark: darkly
      light: flatly
    css: styles.css
editor: visual

execute:
  freeze: auto

